configfile: "config/config.yaml"

rule all:
    input:
        "results/report.html"

# 1. Fetch Reference (Using user's script)
rule fetch_reference:
    output:
        fasta="resources/Tarsius/reference.fasta",
        gbk="resources/Tarsius/reference.gbk"
    params:
        species=config["species_name"],
        email=config["email"],
        organelle_type=config.get("organelle_type", "mitochondrion"),
        expand="--expand" if config.get("expand_search", False) else "",
        min_len=config.get("min_genome_length", 10000),
        max_len=config.get("max_genome_length", 200000)
    conda:
        "envs/analysis.yaml"
    shell:
        """
        python workflow/scripts/fetch_organelle_ref.py \
            --species "{params.species}" \
            --email "{params.email}" \
            --organelle_type {params.organelle_type} \
            --min_len {params.min_len} \
            --max_len {params.max_len} \
            {params.expand} \
            --output_fasta {output.fasta} \
            --output_gbk {output.gbk}
        """

# 2. RSCU Analysis
rule rscu_analysis:
    input:
        "resources/Tarsius/result_cleaned-tRNA.fas"
    output:
        table="results/rscu/rscu.tsv",
        plot="results/rscu/rscu_plot.png"
    params:
        code=config["genetic_code"]
    conda:
        "envs/analysis.yaml"
    shell:
        "python workflow/scripts/calculate_rscu.py {input} {output.table} {output.plot} {params.code}"

# 3. Codon Start/Stop Analysis
rule codon_analysis:
    input:
        "resources/Tarsius/result_cleaned-tRNA.fas"
    output:
        "results/codons/start_stop_stats.txt"
    params:
        code=config["genetic_code"]
    conda:
        "envs/analysis.yaml"
    shell:
        "python workflow/scripts/analyze_codons.py {input} {output} {params.code}"

# 4. Ka/Ks Analysis (Pairwise alignment)
rule kaks_analysis:
    input:
        sample="resources/Tarsius/result_cleaned-tRNA.fas",
        ref="resources/Tarsius/reference.gbk"
    output:
        summary="results/kaks/kaks_summary.tsv",
        aln_dir=directory("results/kaks/alignments")
    conda:
        "envs/analysis.yaml"
    shell:
        "python workflow/scripts/run_kaks_analysis.py {input.sample} {input.ref} {output.aln_dir} {output.summary}"

# 5. Phylogeny Preparation (Supermatrix)
rule prepare_phylo:
    input:
        sample="resources/Tarsius/result_cleaned-tRNA.fas",
        ref="resources/Tarsius/reference.gbk"
    output:
        supermatrix="results/phylogeny/supermatrix.fasta",
        partition="results/phylogeny/partition.nex"
    conda:
        "envs/analysis.yaml"
    shell:
        "python workflow/scripts/prepare_phylo.py {input.sample} {input.ref} {output.supermatrix} {output.partition}"

# 6. Phylogeny Tree (IQ-TREE)
rule phylogeny_tree:
    input:
        aln="results/phylogeny/supermatrix.fasta",
        part="results/phylogeny/partition.nex"
    output:
        tree="results/phylogeny/partition.nex.contree",  # IQ-TREE uses partition file prefix with -spp
        log="results/phylogeny/partition.nex.log"
    params:
        out_prefix="results/phylogeny/supermatrix.fasta"
    conda:
        "envs/phylo.yaml"
    threads: 2
    shell:
        # -s alignment -spp partition (allows different speeds) -bb 1000 ultrafast bootstrap -nt AUTO
        # -redo to overwrite previous
        "iqtree -s {input.aln} -spp {input.part} -m GTR+G -bb 1000 -nt {threads} -redo"

# 6b. Plot Phylogenetic Tree
rule plot_tree:
    input:
        tree="results/phylogeny/partition.nex.contree"
    output:
        plot="results/phylogeny/tree_plot.png"
    conda:
        "envs/analysis.yaml"
    shell:
        "python workflow/scripts/plot_tree.py {input.tree} {output.plot}"

# 7. Generate HTML Report
rule generate_report:
    input:
        rscu_plot="results/rscu/rscu_plot.png",
        rscu_table="results/rscu/rscu.tsv",
        codon_stats="results/codons/start_stop_stats.txt",
        kaks_summary="results/kaks/kaks_summary.tsv",
        tree="results/phylogeny/partition.nex.contree",
        tree_plot="results/phylogeny/tree_plot.png",
        gc_plot="results/composition/gc_content_plot.png",
        aa_plot="results/composition/aa_composition_plot.png",
        circos_plot="results/circos/genome_circos.png",
        synteny_plot="results/synteny/synteny_plot.png",
        synteny_summary="results/synteny/synteny_summary.tsv"
    output:
        "results/report.html"
    params:
        species=config["species_name"]
    conda:
        "envs/analysis.yaml"
    shell:
        "python workflow/scripts/generate_html_report.py {input.rscu_plot} {input.rscu_table} {input.codon_stats} {input.kaks_summary} '{params.species}' {output} {input.tree} {input.gc_plot} {input.aa_plot} {input.tree_plot} {input.circos_plot} {input.synteny_plot} {input.synteny_summary}"

# 8. Composition Analysis (GC & AA)
rule composition_analysis:
    input:
        "resources/Tarsius/result_cleaned-tRNA.fas"
    output:
        gc_plot="results/composition/gc_content_plot.png",
        aa_plot="results/composition/aa_composition_plot.png",
        gc_table="results/composition/gc_content.tsv",
        aa_table="results/composition/aa_composition.tsv"
    conda:
        "envs/analysis.yaml"
    shell:
        "python workflow/scripts/analyze_composition.py {input} results/composition"

# 8b. Generate GenBank for Circos
rule generate_genbank:
    input:
        gff="resources/Tarsius/result.gff",
        fasta="resources/Tarsius/Consensus.fasta"
    output:
        gbk="resources/Tarsius/result.gbk"
    conda:
        "envs/analysis.yaml"
    shell:
        "python workflow/scripts/mitos_to_genbank.py {input.gff} {input.fasta} {output.gbk}"

# 9. Circos Genome Visualization (native circos from circos.ca)
rule circos_visualization:
    input:
        gbk="resources/Tarsius/result.gbk"
    output:
        plot="results/circos/genome_circos.png"
    conda:
        "envs/circos.yaml"
    shell:
        "python workflow/scripts/create_circos_plot.py {input.gbk} {output.plot}"

# 10. Synteny Analysis
rule synteny_analysis:
    input:
        sample="resources/Tarsius/result_cleaned-tRNA.fas",
        reference="resources/Tarsius/reference.fasta"
    output:
        plot="results/synteny/synteny_plot.png",
        summary="results/synteny/synteny_summary.tsv"
    conda:
        "envs/synteny.yaml"
    threads: 2
    shell:
        "python workflow/scripts/run_synteny_analysis.py {input.sample} {input.reference} {output.plot} {output.summary}"
